name: Upload Python Package

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build package
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade --progress-bar off build pdm-backend twine
          python3 -m build --no-isolation
          twine upload --disable-progress-bar --verbose dist/*
